---
# code: language=ansible
# tasks file for trng_env role

- name: Configuration block to setup training environment
  become: true
  tags:
    - trng_env
    - trng_env_config
  block:
    - name: Ensure UFW OpenSSH rule is present
      community.general.ufw:
        rule: allow
        port: '22'
        state: enabled
      tags:
        - trng_env_ufw

    - name: Allow SSH from eth0 to podman0 container network
      community.general.ufw:
        route: true
        rule: allow
        interface_in: eth0
        interface_out: podman0
        proto: tcp
        to_port: 22
        to_ip: 10.88.0.0/16
        comment: "Erlaube SSH-Verkehr von eth0 zu Podman-Containern"
      tags:
        - trng_env_ufw

    - name: Ensure trainings image build path exists
      ansible.builtin.file:
        path: "{{ trng_env_image_build_path }}"
        state: directory
        mode: '0755'
        owner: root
        group: root
      tags:
        - trng_env_image_build

    - name: Copy entrypoint skript
      ansible.builtin.copy:
        src: "entrypoint.sh"
        dest: "{{ trng_env_image_build_path }}/entrypoint.sh"
        owner: root
        group: root
        mode: '0644'
      tags:
        - trng_env_image_build

    - name: Copy training image Dockerfile and related files
      ansible.builtin.template:
        src: "Dockerfile.j2"
        dest: "{{ trng_env_image_build_path }}/Dockerfile"
        owner: root
        group: root
        mode: '0644'
      tags:
        - trng_env_image_build

    - name: Build the Podman training image
      containers.podman.podman_image:
        name: "{{ trng_env_training_image }}"
        path: "{{ trng_env_image_build_path }}"
        build:
          cache: false
          force_rm: true
        state: present
        executable: podman
      tags:
        - trng_env_image_build
